# syntax=docker/dockerfile:1

# ============================================================
# Base — pin Node and enable pnpm via corepack (lockfile v9 -> pnpm 9/10)
# ============================================================
FROM node:20-alpine AS base
# libc6-compat helps some native deps run on Alpine's musl libc.
RUN apk add --no-cache libc6-compat
RUN corepack enable
WORKDIR /app

# ============================================================
# Dependencies — install with a frozen lockfile for reproducible builds
# ============================================================
FROM base AS deps
COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

# ============================================================
# Builder — compile the Next.js app into a standalone bundle
# ============================================================
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Disable Next.js telemetry during the image build.
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm build

# ============================================================
# Runner — minimal runtime image, runs as a non-root user
# ============================================================
FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create an unprivileged user to run the server.
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

# Public assets (images, fonts, the gifs you preload, etc.).
COPY --from=builder /app/public ./public

# Standalone output: the server + only the node_modules it needs.
# --chown ensures the runtime user can read the files.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
# Bind to all interfaces so the container is reachable from the host.
ENV HOSTNAME="0.0.0.0"

# server.js is generated by Next.js in the standalone output.
CMD ["node", "server.js"]
