import type { Metadata } from "next";
import { Fredoka } from 'next/font/google'
import "./globals.css";


const fredoka = Fredoka({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-fredoka',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${fredoka.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
